// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgJC7Dao4K67_RpJwd549MyDjupjDlUCw',
    appId: '1:661390553081:web:4d25d6774225272cca1728',
    messagingSenderId: '661390553081',
    projectId: 'study-success-diary',
    authDomain: 'study-success-diary.firebaseapp.com',
    storageBucket: 'study-success-diary.firebasestorage.app',
    measurementId: 'G-KGB091TH07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABg5RTjeJvdYvav85JSUhzPDwI2iWQzWY',
    appId: '1:661390553081:android:f2b2865d0d06069dca1728',
    messagingSenderId: '661390553081',
    projectId: 'study-success-diary',
    storageBucket: 'study-success-diary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFVLkX41c9iJb-N6dVkrbzrCAkqOd1Zyg',
    appId: '1:661390553081:ios:457bf188080163a6ca1728',
    messagingSenderId: '661390553081',
    projectId: 'study-success-diary',
    storageBucket: 'study-success-diary.firebasestorage.app',
    iosClientId: '661390553081-qp3llfeko6paqlh5el4tfb6kf6t6cf72.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAchievementDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFVLkX41c9iJb-N6dVkrbzrCAkqOd1Zyg',
    appId: '1:661390553081:ios:457bf188080163a6ca1728',
    messagingSenderId: '661390553081',
    projectId: 'study-success-diary',
    storageBucket: 'study-success-diary.firebasestorage.app',
    iosClientId: '661390553081-qp3llfeko6paqlh5el4tfb6kf6t6cf72.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyAchievementDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgJC7Dao4K67_RpJwd549MyDjupjDlUCw',
    appId: '1:661390553081:web:424c53a3b20f1765ca1728',
    messagingSenderId: '661390553081',
    projectId: 'study-success-diary',
    authDomain: 'study-success-diary.firebaseapp.com',
    storageBucket: 'study-success-diary.firebasestorage.app',
    measurementId: 'G-6TY7JXEVMR',
  );

}